### ISSUE TITLE
Change over to be built on Ember 2 & pods.

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/ember-object#1]

**Comment by gaand** [comment]
@MattB-GA-Boston Would you please add a little detail for those of us less in the know.  Thanks!

**Comment by jrhorn424** [comment]
I can do that! `ember-cli` didn't ship with Ember 2.0 last week. This week, it does. These materials were written with Ember 1.13 in mind.

There's a special kind of dependency hell going on here, and it might actually have to do with the version of `node` and `npm` @MattB-GA-Boston is using, not the version of Ember as I had originally suspected when this issue was filed.

Short story: our lessons should have been built using `node 4.2.2` and something like `npm 2.14.10` based on the node lessons we taught this time around. This lesson was generated using `node 5.0.0` and something above `npm 3.x`. That means version numbers are off in package.json and bower.json.

Follow this instead: https://github.com/ga-wdi-boston/ember-starter
